default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: graphql-todo-api_development

test:
  <<: *default
  database: graphql-todo-api_test

production:
  <<: *default
  database: graphql-todo-api_production
